let hobby = "Praying";
let test = new String("Jesus");
typeof test;
test.length;
let p = "Royalty";
p.length;
p.bold();
p.charAt(1);
let example = "Chancellor";
example.charAt(0);
["Beans" "Soup" "Salad" "Meat" "Rice" "Spaghetti"];
example.charAt(1);
example.charAt(100);
example.substring(1, 4);
example.substring(1, 2);
example.substring();
typeof example;
"Any string".length;
22, 22.567, 96869749834784705;
let age = 30;
typeof age;
let height = 90;
typeof height;
let sum = 90 + 10;
alert(sum);
let diff = 90 -10;
console.log(diff);
let product = 90 * 10;
console.log(product);
let division = 90 / 10;
console.log(division);
let remainder = 90 % 10;
console.log(remainder);
